### ISSUE TITLE
Reboot issues

### ISSUE THREAD

**Issue by Semetra22** [yunnanpl/esp32_python_eq3#13]
After uploading the code via ampy, it runs fine. Autodiscovery also works without problems and the thermostats can be controlled via Homeassistant.
However, as soon as I disconnect the ESP32 from the power (to position it in a central location) and then restart it, neither the web interface can be opened, nor are values shared via Mqtt.

Does anyone have an idea what I am doing wrong?

edit: The IP address is reachable, although with some packet losses.

**Comment by yunnanpl** [comment]
Hi, network has to be available, together with MQTT and NTP. Otherwise it will not boot well (at all, assuming that the network has an issue).
Is there some kind of firewall, or NTP/MQTT is not available ?

If the IP is available, then try to connect with WebREPL (first, enable it):
http://micropython.org/webrepl/
Then you should see some logs, and see if the connection works well.

IMPORTANT: I assume you use some other power supply, than for uploading, make sure that it provides enough power (try some other one). Maybe the voltage is not enough, or not stable, that is why it does not boot well.
